---
title: "R Notebook"
output: html_notebook
---

```{r}
# se requiere la instalacion de java
library(arules)
library(Matrix)
library(readxl)
library(tibble)
library(ggplot2)
```

```{r}
# en el ultimo año se añadieron nuevas carácteristicas, para
# usar la mayor cantidad de datos estos se omitieron

columnas20 = list(
              c('departamento', 'numeric'),	
              c('municipio', 'numeric'),	
              c('estrato', 'text'),	
              c('zona',	'text'),	
              c('etapa', 'text'),	
              c('segmento', 'text'),	
              c('polig', 'text'),	
              c('universo_nest', 'numeric'),	
              c('universo_nzo', 'numeric'),	
              c('muestra_nzo', 'numeric'),	
              c('muestra_n', 'numeric'),	
              c('expansor', 'numeric'),	
              c('maiz_c', 'numeric'),	
              c('frijol_c',	'numeric'),	
              c('arroz_c', 'numeric'),	
              c('otros_usos', 'numeric'),	
              c('maiz_p', 'numeric'),	
              c('frijol_p', 'numeric'),	
              c('arroz_p', 'numeric'))
  

columnas_ant = list(
              c('departamento', 'numeric'),	
              c('municipio', 'numeric'),	
              c('estrato', 'text'),	
              c('etapa', 'text'),	
              c('segmento', 'text'),	
              c('universo_nest', 'numeric'),	
              c('muestra_n', 'numeric'),	
              c('expansor', 'numeric'),	
              c('maiz_c', 'numeric'),	
              c('frijol_c',	'numeric'),	
              c('arroz_c', 'numeric'),	
              c('otros_usos', 'numeric'),	
              c('maiz_p', 'numeric'),	
              c('frijol_p', 'numeric'),	
              c('arroz_p', 'numeric'))


# se toman las columnas comunes a ambos conjuntos
sel_columnas = intersect(
        sapply(columnas20, function(l) l[1]),
        sapply(columnas_ant, function(l) l[1]))


# funcion para leer los datos y colocar los tipos de datos
leer_excel <- function(nombre, columnas){
  path <- paste('.\\', nombre, sep='')
  
  df <- read_xlsx(
        path=path,
        skip=6,
        col_names=sapply(columnas, function(lista) lista[1]),
        col_types=sapply(columnas, function(lista) lista[2])
        )
  return(df[, (names(df) %in% sel_columnas)])
 }


```

```{r}
# se unen los dataframes
df <- rbind(
      leer_excel('base20.xlsx', columnas20),
      leer_excel('base19.xlsx', columnas_ant),
      leer_excel('base17.xlsx', columnas_ant))


# se eliminan las filas que contengan ML Y M, son menos de 20
df <- df[, !(names(df) %in% c('universo_nest',
                              'muestra_n','expansor', 'segmento'))]
df <- df[!apply(df == 'ML' | df == 'M', 1, any),]

df$etapa <- as.numeric(df$etapa)
```

```{r}
# filtrar los valores extremos
df = df[df$maiz_c < (3*sd(df$maiz_c) + median(df$maiz_c))
   &
   df$frijol_c < (3*sd(df$frijol_c) + median(df$frijol_c))
   &
   df$arroz_c < (3*sd(df$arroz_c) + median(df$arroz_c)),]

df_kmeans = data.frame(df)
```

```{r}

# se discretizan los datos de las areas con el metodo de cluster
df$maiz_c = discretize(df$maiz_c, method='cluster', breaks=12)
df$frijol_c = discretize(df$frijol_c, method='cluster', breaks=12)
df$arroz_c = discretize(df$arroz_c, method='cluster', breaks=6)
df$otros_usos = discretize(df$otros_usos, method='cluster', breaks=12)

df$maiz_p = discretize(df$maiz_p, method='cluster', breaks=12)
df$frijol_p = discretize(df$frijol_p, method='cluster', breaks=12)
df$arroz_p = discretize(df$arroz_p, method='cluster', breaks=6)

df <- as.data.frame(lapply(df, as.factor))
```

```{r}

# primer algoritmo, apriori

reglas <- apriori(df, parameter=list(support=0.1, confidence=0.65))
x <- as(reglas, 'data.frame')
x[grepl("(?=departamento=17)", x$rules, perl=TRUE),]
```

```{r}
# segundo algoritmo fpgrowth

reglas <- fim4r(df, method='fpgrowth', target='rules', supp=.1, conf=.8)
xy <- as(reglas, 'data.frame')
xy
```

```{r}
xy[grepl("(?==> {arroz_p)", xy$rules, perl=TRUE),]
```

```{r}
# tercer algoritmo kmeans  


# se elige cuantos grupos se va a utilizar

# se escalan los valores
dd <- df_kmeans[, !(names(df_kmeans) %in% c('estrato','departamento','municipio'))]

dd[, names(dd) %in% c('frijol_p', 'frijol_c', 'maiz_p','maiz_c', 'arroz_p', 'arroz_c','otros_usos')] <- scale(dd[, names(dd) %in% c('frijol_p','frijol_c',                             'maiz_p','maiz_c', 'arroz_p', 'arroz_c','otros_usos')])

# cantidad de grupos
n <- 15

# inicializa el error
wss <- numeric(10)


# iterar incrementando los grupos
for (i in 1:n) {
  # entrena el modelo en: km.out
  salida <- kmeans(dd, centers = i, nstart = 10)
  # guarda la suma de cuadrados en wss
  wss[i] <- salida$tot.withinss
}

# plotea la suma de cuadrados
wss_df <- tibble(clusters = 1:n, wss = wss)


scree_plot <- ggplot(wss_df, aes(x = clusters, y = wss, group = 1)) +
    geom_point(size = 4)+
    geom_line() +
    scale_x_continuous(breaks = c(2, 4, 6, 8, 10)) +
    xlab('numero de cluester')
scree_plot

salida = kmeans(dd, centers=4, nstart=20)
dd$clase <- factor(salida$cluster)
```

```{r}
ggplot(dd, aes(x=frijol_c, y=maiz_c, color=clase)) +
  geom_point(alpha=.8) 

dd
```

```{r}
ggplot(dd, aes(x=otros_usos, y=etapa, color=clase)) +
  geom_point(alpha=.5) 

 
dd
```
