---
title: "R Notebook"
output: html_notebook
---

```{r}
# se requiere la instalacion de java
library(caret)
library(arules)
library(Matrix)
library(readxl)
library(tibble)
library(rpart)
library(rpart.plot)
library(randomForest)

```

```{r}
# en los datasets, el ultimo año se añadieron nuevas carácteristicas, 3 nuevas caracteristicas
# se omitieron por solo en el ultimo dataset 

columnas20 = list(
              c('departamento', 'numeric'),	
              c('municipio', 'numeric'),	
              c('estrato', 'text'),	
              c('zona',	'text'),	
              c('etapa', 'text'),	
              c('segmento', 'text'),	
              c('polig', 'text'),	
              c('universo_nest', 'numeric'),	
              c('universo_nzo', 'numeric'),	
              c('muestra_nzo', 'numeric'),	
              c('muestra_n', 'numeric'),	
              c('expansor', 'numeric'),	
              c('maiz_c', 'numeric'),	
              c('frijol_c',	'numeric'),	
              c('arroz_c', 'numeric'),	
              c('otros_usos', 'numeric'),	
              c('maiz_p', 'numeric'),	
              c('frijol_p', 'numeric'),	
              c('arroz_p', 'numeric'))
  

columnas_ant = list(
              c('departamento', 'numeric'),	
              c('municipio', 'numeric'),	
              c('estrato', 'text'),	
              c('etapa', 'text'),	
              c('segmento', 'text'),	
              c('universo_nest', 'numeric'),	
              c('muestra_n', 'numeric'),	
              c('expansor', 'numeric'),	
              c('maiz_c', 'numeric'),	
              c('frijol_c',	'numeric'),	
              c('arroz_c', 'numeric'),	
              c('otros_usos', 'numeric'),	
              c('maiz_p', 'numeric'),	
              c('frijol_p', 'numeric'),	
              c('arroz_p', 'numeric'))


# se toman las columnas comunes a ambos conjuntos
sel_columnas = intersect(
        sapply(columnas20, function(l) l[1]),
        sapply(columnas_ant, function(l) l[1]))


# funcion para leer los datos y colocar los tipos de datos
leer_excel <- function(nombre, columnas){
  path <- paste('.\\', nombre, sep='')
  
  df <- read_xlsx(
        path=path,
        skip=6,
        col_names=sapply(columnas, function(lista) lista[1]),
        col_types=sapply(columnas, function(lista) lista[2])
        )
  return(df[, (names(df) %in% sel_columnas)])
 }

```

```{r}
# se unen los dataframes
df <- rbind(
      leer_excel('base20.xlsx', columnas20),
      leer_excel('base19.xlsx', columnas_ant),
      leer_excel('base17.xlsx', columnas_ant))


# se eliminan las filas que contengan ML Y M, son menos de 20
df <- df[, !(names(df) %in% c('universo_nest',
                              'muestra_n','expansor', 'segmento'))]
df <- df[!apply(df == 'ML' | df == 'M', 1, any),]

df$etapa <- as.numeric(df$etapa)
```

```{r}
# arboles de decision
```

```{r}
# arbol de prediccion de produccion de frijol
df_frif = data.frame(df)
df_frif$frijol_p = discretize(df_frif$frijol_p, method='cluster', breaks=5)
arbol_frif <- rpart( frijol_p~ 
                 municipio + 
                 estrato + 
                 etapa + 
                 maiz_c + 
                 frijol_c +
                 arroz_c + 
                 otros_usos + 
                 maiz_p + 
                 departamento + 
                 arroz_p,
          
               data=df_frif, 
               method='class')
```

```{r}
# predicción de rangos de frijol_p
rpart.plot(arbol_frif, 
           type=2, 
           extra=0, 
           under=TRUE, 
           fallen.leaves=TRUE, 
           box.palette='BuGn', 
           main='Prediccion de rangos de frijol_p', 
           cex=.45)

'para este arbol lo unico importante para saber la cantidad de frijol producido el la cantidad
de frijol cultivado.

se esperaba que hubiera algo mas de peso en las variables, como puede ser el departamento, o 
el tipo de superfice utilizada "estrato" [A, B, C, D] o incluso la etapa de cosechas relacionadas con las lluvias [etapa1, etapa2, etapa3]

el arbol obtenido es muy simple, asigna un rango de produccion a cierto tamanio de cultivo, cada nodo un poco mayor que el anterior,
lo mismo con los rangos'
```

```{r}
# arbol de prediccion de estrato
arbol_estrato <- rpart(estrato ~ 
                 municipio + 
                 departamento + 
                 etapa + 
                 maiz_c + 
                 frijol_c +
                 arroz_c + 
                 otros_usos + 
                 maiz_p + 
                 frijol_p + 
                 arroz_p,
          
               data=df, 
               method='class')
```

```{r}
# predicción del estrato
rpart.plot(arbol_estrato, 
           type=2, 
           extra=0, 
           under=TRUE, 
           fallen.leaves=TRUE, 
           box.palette='BuGn', 
           main='Prediccion del estrato', 
           cex=.45)


'para este arbol las variables mas significativas son [otros_usos, departamento]

Es mas complejo que el arbol de frijol_p, aunque como con el anterior, se esperaba que fusen 
mas relevantes las demas caracteristicas de superficie y produccion

estrato A:
      se obtiene en dos puntos del arbol
              el primero cuando la superficie usada por otros_usos esta entre [7.8, 26)
              el segundo cuando la superficie usada por otros_usos es menor a 1.9 y el departamento es menor al 13
estrato B:
      solo existe una forma de llegar a B
              la superficie usada por otros_usos tiene que estar entre [1.9, 7.8]

estrato C:
      solo existe una forma de llegar a C
            la superficie usada por otros_usos tiene que estar entre (26, 58)
estrato D:
      existen dos formas de llegar a D
            cuando la superficie usada por otros_usos es mayor a 58
            cuando la superficie usada por otros_usos es menor a 1.9 y el departamento es mayor o igual al 13
            
            
            
            
            
situaciones
      puede ser util para una empresa que vende feritizantes o una empresa que se dedique a habilitar espacios,
      encontrar nuevos clientes en funcion de lo poco o mucho que usen las tierras para otros cultivos que no sean
      el maiz, frijol o arroz, y dependiendo del departamento, enfocados a los estratos C y D.
      
      tambien puede ser interesante hacer algun tipo de campaña de mejora de conocimientos de ciembras enfocada a los productores 
      con estratos de tipo C y D, que no aprovechan del todo las tierras


'
```

```{r}
# arbol de prediccion de etapa
arbol <- rpart(etapa ~ 
                 municipio + 
                 departamento + 
                 estrato + 
                 maiz_c + 
                 frijol_c +
                 arroz_c + 
                 otros_usos + 
                 maiz_p + 
                 frijol_p + 
                 arroz_p,
          
               data=df, 
               method='class')
```

```{r}
rpart.plot(arbol, 
           type=2, 
           extra=0, 
           under=TRUE, 
           fallen.leaves=TRUE, 
           box.palette='BuGn', 
           main='Prediccion de la etapa', 
           cex=.45)

'para este arbol las variables mas significativas son [frijol_c, departamento]

este no es un buen arbol, el uso de un departamento como forma de diferenciar una epoca del año es ilogica
el area plantada vs la produccion deberia de ser un mejor indicio de la epoca (suposicion: en epocas muy lluviosas mayor produccion).
Parece que el planteamiento anterior no tiene el suficiente peso como para que el arbol lo tubiera en cuenta.
'
```

```{r}
# predicciones con los arboles de decision
```

```{r}
# de FP-Growth
# {departamento=17,frijol_c=[0,0.0782),arroz_c=[0,0.0647)} => {frijol_p=[0,1.94)}
pred <- data.frame(#frijol_p=c(1), 
                   municipio=c(5), 
                   estrato=c('A'), 
                   etapa=c(1), 
                   maiz_c=c(0),
                   frijol_c=c(0),
                   arroz_c=c(1),
                   otros_usos=c(1),
                   maiz_p=c(1),
                   departamento=c(17),
                   arroz_p=c(1)
                   )

predict(arbol_frif, pred, type='class')
```

```{r}
# de FP-Growth
# 	{frijol_c=[0,0.0782),arroz_c=[0,0.0647),otros_usos=[91.1,144),arroz_p=[0,1.52)} => {estrato=D}	

pred <- data.frame(frijol_p=c(1), 
                   municipio=c(5), 
                   #estrato=c('A'), 
                   etapa=c(1), 
                   maiz_c=c(0),
                   frijol_c=c(0),
                   arroz_c=c(1),
                   otros_usos=c(100),
                   maiz_p=c(1),
                   departamento=c(17),
                   arroz_p=c(1)
                   )

predict(arbol_estrato, pred, type='class')
```

```{r}
# de FP-Growth
# {maiz_c=[0,0.391),frijol_c=[0,0.0782),arroz_c=[0,0.0647),otros_usos=[22.8,31),frijol_p=[0,1.94),arroz_p=[0,1.52)} => {estrato=A}
pred <- data.frame(frijol_p=c(1), 
                   municipio=c(15), 
                   #estrato=c('A'), 
                   etapa=c(1), 
                   maiz_c=c(0.3),
                   frijol_c=c(0),
                   arroz_c=c(1),
                   otros_usos=c(25),
                   maiz_p=c(1),
                   departamento=c(17),
                   arroz_p=c(1)
                   )

predict(arbol_estrato, pred, type='class')
```

```{r}
# de FP-Growth
# {frijol_c=[0,0.0782),arroz_c=[0,0.0647),otros_usos=[47.3,66.7),frijol_p=[0,1.94),arroz_p=[0,1.52)} => {estrato=C}
pred <- data.frame(frijol_p=c(1), 
                   municipio=c(15), 
                   #estrato=c('A'), 
                   etapa=c(1), 
                   maiz_c=c(0.3),
                   frijol_c=c(0),
                   arroz_c=c(1),
                   otros_usos=c(50),
                   maiz_p=c(1),
                   departamento=c(17),
                   arroz_p=c(1)
                   )

predict(arbol_estrato, pred, type='class')
```

```{r}
# arbol de produccion de arroz
df_arr = data.frame(df)
df_arr$arroz_p = discretize(df_frif$arroz_p, method='cluster', breaks=5)
arbol_arr <- rpart( arroz_p~ 
                 municipio + 
                 estrato + 
                 etapa + 
                 maiz_c + 
                 frijol_c +
                 arroz_c + 
                 otros_usos + 
                 maiz_p + 
                 departamento +
                 estrato +
                 frijol_p,
          
               data=df_arr, 
               method='class') 

# FP-Growth
# {departamento=17,maiz_c=[0,0.391),frijol_c=[0,0.0782),arroz_c=[0,0.0647),maiz_p=[0,31.2),frijol_p=[0,1.94)} => {arroz_p=[0,1.52)}
pred <- data.frame(frijol_p=c(1), 
                   municipio=c(15), 
                   estrato=c('A'), 
                   etapa=c(1), 
                   maiz_c=c(0.3),
                   frijol_c=c(0),
                   arroz_c=c(1),
                   otros_usos=c(50),
                   maiz_p=c(1),
                   departamento=c(17)
                   #arroz_p=c(1)
                   )

predict(arbol_arr, pred, type='class')
```

```{r}
# Predicción por medio de bosques aleatorios
```

```{r}
# preparacion de la data, se elige cual va a ser la variable dependiente
data = data.frame(df)
data$estrato = as.factor(data$estrato)
set.seed(10)
data = data[sample(1: nrow(data)), ]


```

```{r}
# se genera la division de entrenamiento y validacion
indice = sample(1:nrow(data), .8*nrow(data))
train = data[indice, ]
test = data[-indice,]
```

```{r}
# bosque aleatorio para el estrato
bosque_estrato = randomForest(estrato ~ 
                       municipio + 
                       departamento + 
                       etapa + 
                       maiz_c + 
                       frijol_c +
                       arroz_c + 
                       otros_usos + 
                       maiz_p + 
                       frijol_p + 
                       arroz_p,
                      
                      data=train,
                      ntree = 100,
                      mtry = 5)
```

```{r}
# bosque aleatorio para el frijol_p
bosque_frijol_p = randomForest(frijol_p ~ 
                       municipio + 
                       departamento + 
                       etapa + 
                       maiz_c + 
                       frijol_c +
                       arroz_c + 
                       otros_usos + 
                       maiz_p + 
                       estrato + 
                       arroz_p,
                      
                      data=train,
                      ntree = 100,
                      mtry = 5)
```

```{r}
# predicciones de bosque aleatorio frijol_p
# el arbol de decision con estos mismos parametros nos dio el rango: [0,25.7)
# el valor predicho por el modelo entra en el intervalo
pred <- data.frame(frijol_p=c(1), 
                   municipio=c(5), 
                   estrato=test[test$estrato == "A", ]$estrato[1], 
                   etapa=c(1), 
                   maiz_c=c(0),
                   frijol_c=c(0),
                   arroz_c=c(1),
                   otros_usos=c(1),
                   maiz_p=c(1),
                   departamento=c(17),
                   arroz_p=c(1)
                   )


predict(bosque_frijol_p, pred, type='class')
```

```{r}
# predicciones de bosque aleatorio estrato
# el arbol de decision con estos mismos parametros nos dio: el estrato D
# el modelo predijo el estrato D, que concuerda con el anterior arbol
pred <- data.frame(frijol_p=c(1), 
                   municipio=c(5), 
                   estrato=test[test$estrato == "A", ]$estrato[1], 
                   etapa=c(1), 
                   maiz_c=c(0),
                   frijol_c=c(0),
                   arroz_c=c(1),
                   otros_usos=c(100),
                   maiz_p=c(1),
                   departamento=c(17),
                   arroz_p=c(1)
                   )

predict(bosque_estrato, pred, type='class')
```

```{r}

```
